### ISSUE TITLE
Is there a way to decompile the actionmaps.xml from Crysis Remastered?

### ISSUE THREAD

**Issue by ghost** [Markemp/CryXmlViewer#1]
I'm trying to remove the toggle functions from some of the actions.

**Comment by Markemp** [comment]
Not that I'm aware of.  The only actionmaps.xml file I'm aware of is under libs\config\profiles\default, and it's just an empty xml file.

**Comment by ghost** [comment]
Do you know where the key bindings for the active player profile are stored?

**Comment by Markemp** [comment]
I have no idea.  Sorry. :(

If I had to guess, it's probably in the user directory somewhere.  It won't be in the game files.

**Comment by Markemp** [comment]
Closing issue.
